#!/usr/bin/python3

def raise_exception():
    a = 45
    b = "text"
    result = a + b
    print("{}".format(result))
